pipeline:
  name: Build Playwright-test
  identifier: Build_shubham_harness_Playwright_test_1778065341337
  projectIdentifier: default_project
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo Welcome Message
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: echo "Welcome to Harness CI"
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1778065330241
        repoName: shubham-harness/Playwright-test
        build: <+input>
